### ISSUE TITLE
不能进行 set 赋值操作

### ISSUE THREAD

**Issue by hackjie** [webfrogs/HandOfTheKing#1]
你好，想请问怎么写可以实现 set 方法，如果是对 UIView 拓展加上 width 属性

view.hand.width = 200 

会有'hand' read-only 报错

**Comment by webfrogs** [comment]
这个场景不适合用 HandOfTheKing 这种方式来做。

**Comment by hackjie** [comment]
嗯嗯 看到这个库就想对现有的 extension 做一层命名空间封装，结果发现 get 是可以的，set 不行，楼主对项目里的 extension 做封装了么，还是加了前缀

**Comment by webfrogs** [comment]
加前缀的做法是用了一个 struct 封装，然后给 NamespaceWrappable 协议一个默认实现。
我提供你这个的一个思路：将 NamespaceWrappable 协议改为 get 和 set。但是由于 extension protocol 不能有存储变量，所以要自己实现协议了。

**Comment by hackjie** [comment]
谢谢
